apiVersion: v1
kind: Secret
metadata:
  name: pmm-secret
  namespace: kube-system
  labels:
    app.kubernetes.io/name: pmm
type: Opaque
data:
# base64 encoded password
# encode some password: `echo -n "12345679" | base64`
    PMM_ADMIN_PASSWORD: MTIzNDU2Nzk=
